### ISSUE TITLE
Not working on Windows 10 with python 3.8

### ISSUE THREAD

**Issue by ronlievens** [kitplummer/clikan#11]
pip install clikan
Collecting clikan
  Using cached https://files.pythonhosted.org/packages/fc/15/0b12cf336843c2e8022ae9aae4767fa6832b17239fb4eb1628f943becfea/clikan-0.0.4-py3-none-any.whl
Requirement already satisfied: pyyaml in c:\python38\lib\site-packages (from clikan) (5.3.1)
Requirement already satisfied: terminaltables in c:\python38\lib\site-packages (from clikan) (3.1.0)
Requirement already satisfied: Click in c:\python38\lib\site-packages (from clikan) (7.1.1)
Installing collected packages: clikan
Successfully installed clikan-0.0.4

clikan configure
Traceback (most recent call last):
  File "c:\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python38\Scripts\clikan.exe\__main__.py", line 9, in <module>
  File "c:\python38\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\python38\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\python38\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python38\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python38\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\python38\lib\site-packages\clikan.py", line 84, in configure
    path = "%s/.clikan.dat" % os.environ['HOME']
  File "c:\python38\lib\os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'HOME'

**Comment by pinksocks** [comment]
You are missing a 'HOME' environment variable.

**Comment by ronlievens** [comment]
Thanks, creating an 'User variable' with the value '%HOMEDRIVE%%HOMEPATH%' solves this issue.
(User variable is the top half of the 'Environment Variables')

**Comment by kitplummer** [comment]
Rad.  Thanks!  Definitely lets me know I should probably add a Windows test in GH Actions.  @ronlievens how did you install Python btw?

**Comment by ronlievens** [comment]
> Rad. Thanks! Definitely lets me know I should probably add a Windows test in GH Actions. @ronlievens how did you install Python btw?

On Windows I use https://chocolatey.org (choco install python)

**Comment by kitplummer** [comment]
Thanks!  Gonna close the issue.  If you have any other issues - re-open or create a new one please.
