### ISSUE TITLE
Invalid parms not handled for delete

### ISSUE THREAD

**Issue by kitplummer** [kitplummer/clikan#44]
```
❯ clik d test
Traceback (most recent call last):
  File "/Users/cplummer8/miniconda3/bin/clikan", line 33, in <module>
    sys.exit(load_entry_point('clikan==0.2.1', 'console_scripts', 'clikan')())
  File "/Users/cplummer8/miniconda3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/cplummer8/miniconda3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/cplummer8/miniconda3/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/cplummer8/miniconda3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/cplummer8/miniconda3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/cplummer8/miniconda3/lib/python3.8/site-packages/clikan-0.2.1-py3.8.egg/clikan.py", line 137, in delete
    item = dd['data'].get(int(id))
ValueError: invalid literal for int() with base 10: 'test'
```

**Comment by kitplummer** [comment]
Fix is in...waiting for release.
