### ISSUE TITLE
[BUG]: `importlib.metadata` error in python 3.11.6

### ISSUE THREAD

**Issue by SeedyROM** [kitplummer/clikan#72]
After running `pip install clikan` and executing the `clikan` command I get this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/clikan", line 5, in <module>
    from clikan import clikan
  File "/usr/local/lib/python3.11/site-packages/clikan.py", line 15, in <module>
    VERSION = importlib.metadata.version('clikan')
              ^^^^^^^^^^^^^^^^^^
AttributeError: module 'importlib' has no attribute 'metadata'
```

**Comment by kitplummer** [comment]
Ayup.  Sorry, I borked it trying to resolve new PyPI and packaging
shenanigans.  I then made it worse in PyPi itself with ghost versions.

Unfortunately I don’t have time to figure it out, specifically the “test”
garbage that would need to get setup in the GHA before actually deploying a
new package.

Basically at some point setup.py fell out of favor and now there are
multiple ways to do it, but none of them actually work as simply as it
should be - to get the version from the file.  I give up, waving the white
flag.  I will try and archive this bad version so at least the install
works.  But I’ve moved in to a Rust-based version of this utility.

**Comment by SeedyROM** [comment]
> But I’ve moved in to a Rust-based version of this utility.

If you could point me to that I'd love to check it out!

**Comment by kitplummer** [comment]
https://github.com/kitplummer/cliban - note that it isn't as featured-up as
this one.  but works as a binary install.

**Comment by kevin-gwyrdh** [comment]
Hi Sorry to read this. 
I have enjoyed very much discovering clikan. Easy to use and a good way to learn a little python hacking it!!! Am I right in thinking that this means
- no further development of clikan
- existing working install is still good to use until something upstream breaks it
- you are working on cliban which uses rust of which I know nothing :-)
Thank you for work you have done here makes a really light solid useful app. Appreciated!

**Comment by tomcotter7** [comment]
not sure if this fixes the problem completely - but you can run it using this library: https://importlib-metadata.readthedocs.io/en/latest/

ref: https://stackoverflow.com/questions/59216175/importerror-cannot-import-name-metadata-from-importlib
